# Generated by Django 5.1.3 on 2024-11-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('anons', models.TextField()),
                ('full_text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images/')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
